begin;

-- Live session checks also protect direct PostgREST access after sign-out.
create function public.dv_session_active() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from auth.sessions
    where user_id = (select auth.uid())
      and id::text = (select auth.jwt()->>'session_id')
      and (not_after is null or not_after > now())
  );
$$;
revoke all on function public.dv_session_active() from public, anon;
grant execute on function public.dv_session_active() to authenticated;

update public.dv_profiles set handle = lower(handle) where handle <> lower(handle);
alter table public.dv_profiles add constraint lowercase_handle check (handle = lower(handle));
-- Abort transaction if an existing reserved handle needs owner-reviewed migration.
alter table public.dv_profiles add constraint reserved_vexa check (handle <> 'vexa');
alter table public.dv_profiles add column updated_at timestamptz not null default now();
alter table public.dv_saved add column updated_at timestamptz not null default now();

create function public.dv_touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;
revoke all on function public.dv_touch_updated_at() from public, anon, authenticated;
create trigger dv_profile_updated before update on public.dv_profiles for each row execute function public.dv_touch_updated_at();
create trigger dv_saved_updated before update on public.dv_saved for each row execute function public.dv_touch_updated_at();

do $$
declare t text;
begin
  foreach t in array array['dv_profiles','dv_favorites','dv_saved','dv_downloads','dv_chats','dv_support','dv_activity'] loop
    execute format('alter policy own_read on public.%I using ((select auth.uid()) = user_id and (select public.dv_session_active()))', t);
    if t <> 'dv_profiles' then
      execute format('alter policy own_delete on public.%I using ((select auth.uid()) = user_id and (select public.dv_session_active()))', t);
      if t <> 'dv_chats' then
        execute format('alter policy own_insert on public.%I with check ((select auth.uid()) = user_id and (select public.dv_session_active()))', t);
      end if;
    end if;
  end loop;
end;
$$;
alter policy own_update on public.dv_profiles
  using ((select auth.uid()) = user_id and (select public.dv_session_active()))
  with check ((select auth.uid()) = user_id and (select public.dv_session_active()));
alter policy own_insert on public.dv_chats with check (
  (select auth.uid()) = user_id and (select public.dv_session_active()) and exists (
    select 1 from public.dv_profiles where user_id = (select auth.uid()) and chat_history_enabled
  )
);

-- Deliberately returns a boolean only; never exposes another member's profile.
create function public.dv_handle_available(candidate text) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.dv_session_active() and candidate ~ '^[a-z0-9_]{3,16}$'
    and candidate <> all(array['admin','administrator','root','support','staff','official','danivex','vexa','api','auth','account','login','register','signup','signin','settings','android','modules','download','downloads','security','verify','system'])
    and not exists (select 1 from public.dv_profiles where handle_normalized = candidate and user_id <> (select auth.uid()));
$$;
revoke all on function public.dv_handle_available(text) from public, anon;
grant execute on function public.dv_handle_available(text) to authenticated;

alter table public.dv_activity drop constraint dv_activity_kind_check;
alter table public.dv_activity add constraint dv_activity_kind_check check (
  kind in ('saved','download_requested','support_requested','account_created','handle_selected','handle_changed','favorite_added')
);
-- Activity can only be generated by database triggers, never forged by a client.
revoke insert on public.dv_activity from authenticated;
revoke insert(kind) on public.dv_activity from authenticated;
create or replace function public.dv_record_activity() returns trigger
language plpgsql security definer set search_path = '' as $$
declare event_kind text;
begin
  if TG_TABLE_NAME = 'dv_profiles' then
    if TG_OP = 'INSERT' then event_kind := 'account_created';
    elsif old.handle is null then event_kind := 'handle_selected';
    else event_kind := 'handle_changed'; end if;
  else
    event_kind := case TG_TABLE_NAME
      when 'dv_saved' then 'saved' when 'dv_downloads' then 'download_requested'
      when 'dv_favorites' then 'favorite_added' when 'dv_support' then 'support_requested'
    end;
  end if;
  if event_kind is not null then
    insert into public.dv_activity(user_id,kind) values (new.user_id,event_kind);
  end if;
  return new;
end;
$$;
revoke all on function public.dv_record_activity() from public, anon, authenticated;
create trigger dv_favorite_activity after insert on public.dv_favorites for each row execute function public.dv_record_activity();
create trigger dv_profile_created_activity after insert on public.dv_profiles for each row execute function public.dv_record_activity();
create trigger dv_handle_activity after update of handle on public.dv_profiles for each row when (old.handle is distinct from new.handle) execute function public.dv_record_activity();

commit;
