const keys = ['account','signin','register','email','password','submit','reset','signout','overview','favorites','saved','downloads','assistant','support','settings','handle','chooseHandle','handleHelp','unavailable','home','loading','save','remove','empty','error','checkEmail','done','language','history','clearHistory','privacy','created','providers','changePassword','changeEmail','deleteAccount','deleteWarning','confirmDelete','subject','message','send','attach','latest','requested','favorite','download','recovery','confirmLink','newPassword','privateContext','storeChat','assistantNotice','close','relogin','savedPreset','ask','noAssistant','supportReceived','saveCurrent']
const values = {
  es: ['Mi cuenta','Iniciar sesión','Crear cuenta','Correo electrónico','Contraseña','Continuar','Recuperar contraseña','Cerrar sesión','Resumen','Favoritos','Guardados','Descargas','Asistente','Soporte','Ajustes','Nombre de usuario','Elige tu @handle','3–16 letras, números o guion bajo. Sin espacios.','Las cuentas todavía no están disponibles.','Volver a DaniVex','Cargando…','Guardar','Eliminar','Todavía no hay elementos.','No se pudo completar. Revisa los datos e inténtalo de nuevo.','Revisa tu correo. Si corresponde, recibirás un enlace.','Cambios guardados.','Idioma','Guardar historial de chat (opcional)','Borrar historial','Privacidad','Cuenta creada','Métodos de acceso','Cambiar contraseña','Cambiar correo','Eliminar cuenta','Esta acción borra tu cuenta y sus datos. No se puede deshacer. Inicia sesión de nuevo antes de continuar.','Escribe DELETE para confirmar','Asunto','Mensaje','Enviar','Adjuntar conversación con mi consentimiento','Últimos 100 registros','Solicitud de descarga','Añadir a favoritos','Descargar Mobilador','Restablecer contraseña','Confirmar enlace','Nueva contraseña (mínimo 12 caracteres)','Permitir consultar solo mis cantidades de favoritos, guardados y descargas','Guardar este intercambio en mi historial','Tu mensaje se enviará a OpenAI. No incluyas contraseñas ni datos sensibles. Las respuestas pueden contener errores.','Cerrar','Vuelve a iniciar sesión para confirmar tu identidad.','Sensibilidad guardada.','Preguntar a DaniVex','El asistente todavía no está disponible.','Solicitud recibida. No hay un plazo de respuesta garantizado.','Guardar configuración'],
  en: ['My account','Sign in','Create account','Email','Password','Continue','Reset password','Sign out','Overview','Favorites','Saved','Downloads','Assistant','Support','Settings','Username','Choose your @handle','3–16 letters, numbers or underscores. No spaces.','Accounts are not available yet.','Back to DaniVex','Loading…','Save','Delete','No items yet.','Could not complete. Check your details and try again.','Check your email. You will receive a link if applicable.','Changes saved.','Language','Save chat history (optional)','Clear history','Privacy','Account created','Sign-in methods','Change password','Change email','Delete account','This permanently deletes your account and its data. Sign in again before continuing.','Type DELETE to confirm','Subject','Message','Send','Attach conversation with my consent','Latest 100 records','Download requested','Add to favorites','Download Mobilador','Reset password','Confirm link','New password (at least 12 characters)','Allow only my favorites, saved and downloads counts','Save this exchange in my history','Your message is sent to OpenAI. Do not include passwords or sensitive data. Answers may contain errors.','Close','Sign in again to verify your identity.','Sensitivity saved.','Ask DaniVex','The assistant is not available yet.','Request received. No response time is guaranteed.','Save setup'],
  it: ['Il mio account','Accedi','Crea account','Email','Password','Continua','Recupera password','Esci','Riepilogo','Preferiti','Salvati','Download','Assistente','Supporto','Impostazioni','Nome utente','Scegli il tuo @handle','3–16 lettere, numeri o trattini bassi. Senza spazi.','Gli account non sono ancora disponibili.','Torna a DaniVex','Caricamento…','Salva','Elimina','Nessun elemento.','Operazione non riuscita. Controlla i dati e riprova.','Controlla la posta. Riceverai un link se applicabile.','Modifiche salvate.','Lingua','Salva cronologia chat (facoltativo)','Cancella cronologia','Privacy','Account creato','Metodi di accesso','Cambia password','Cambia email','Elimina account','Elimina definitivamente account e dati. Accedi di nuovo prima di continuare.','Scrivi DELETE per confermare','Oggetto','Messaggio','Invia','Allega conversazione con il mio consenso','Ultimi 100 record','Download richiesto','Aggiungi ai preferiti','Scarica Mobilador','Reimposta password','Conferma link','Nuova password (almeno 12 caratteri)','Consenti solo i conteggi di preferiti, salvati e download','Salva questo scambio nella cronologia','Il messaggio viene inviato a OpenAI. Non includere password o dati sensibili. Le risposte possono contenere errori.','Chiudi','Accedi di nuovo per verificare la tua identità.','Sensibilità salvata.','Chiedi a DaniVex',"L’assistente non è ancora disponibile.",'Richiesta ricevuta. Non è garantito un tempo di risposta.','Salva configurazione'],
  pt: ['Minha conta','Entrar','Criar conta','E-mail','Senha','Continuar','Recuperar senha','Sair','Resumo','Favoritos','Salvos','Downloads','Assistente','Suporte','Configurações','Nome de usuário','Escolha seu @handle','3–16 letras, números ou sublinhado. Sem espaços.','As contas ainda não estão disponíveis.','Voltar à DaniVex','Carregando…','Salvar','Excluir','Nenhum item ainda.','Não foi possível concluir. Confira os dados e tente novamente.','Confira seu e-mail. Você receberá um link se aplicável.','Alterações salvas.','Idioma','Salvar histórico de chat (opcional)','Limpar histórico','Privacidade','Conta criada','Métodos de acesso','Alterar senha','Alterar e-mail','Excluir conta','Exclui permanentemente sua conta e seus dados. Entre novamente antes de continuar.','Digite DELETE para confirmar','Assunto','Mensagem','Enviar','Anexar conversa com meu consentimento','Últimos 100 registros','Download solicitado','Adicionar aos favoritos','Baixar Mobilador','Redefinir senha','Confirmar link','Nova senha (mínimo 12 caracteres)','Permitir apenas minhas quantidades de favoritos, salvos e downloads','Salvar esta conversa no histórico','Sua mensagem será enviada à OpenAI. Não inclua senhas ou dados sensíveis. Respostas podem conter erros.','Fechar','Entre novamente para confirmar sua identidade.','Sensibilidade salva.','Pergunte à DaniVex','O assistente ainda não está disponível.','Pedido recebido. Não há prazo de resposta garantido.','Salvar configuração'],
}
export const accountCopy = Object.fromEntries(Object.entries(values).map(([lang, row]) => [lang, Object.fromEntries(keys.map((key, i) => [key, row[i]]))]))
for (const [lang, extra] of Object.entries({
  es: { more: 'Cargar más', retry: 'Reintentar', explore: 'Explorar herramientas', activity: 'Actividad reciente' },
  en: { more: 'Load more', retry: 'Try again', explore: 'Explore tools', activity: 'Recent activity' },
  it: { more: 'Carica altri', retry: 'Riprova', explore: 'Esplora strumenti', activity: 'Attività recenti' },
  pt: { more: 'Carregar mais', retry: 'Tentar novamente', explore: 'Explorar ferramentas', activity: 'Atividade recente' },
})) Object.assign(accountCopy[lang], extra)
export function initialLanguage() {
  try { const saved = localStorage.getItem('danivex:language'); if (accountCopy[saved]) return saved } catch { /* Optional preference. */ }
  const code = navigator.language.slice(0, 2)
  return accountCopy[code] ? code : 'es'
}
